"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import Footer from "@/src/components/Footer";
import Header from "@/src/components/Header";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};             /*export*/

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${inter.variable} antialiased`}>
            <Providers>
            <Header />
            <div className=" relative flex size-full min-h-screen flex-col bg-[#111811] dark group/design-root overflow-x-hidden">
                {children}
            </div>
            <Footer />
            </Providers>
        </body>
        </html>
    );
}
